config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :messages, only: [:new, :create]
  resources :website, only: [:index]
  resources :resume, only: [:index]
  root "website#index"
  get 'download_pdf', to: "resume#download_pdf"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
  has_many :tags
  has_many :skills, through: :tags
  enum experience_type: %i[work education]

  scope :work,      -> { where('experience_type', 0) }
  scope :education, -> { where('experience_type', 1) }
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :firstname, :email, :phone_number, :body
  validates :name, :firstname, :email, :phone_number, :body, presence: true
  validates :email, format: /\A[^@]+@[^@]+\z/
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :tags
  has_many :experiences, through: :tags
  enum category: %i[language framework other]
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :skill
  belongs_to :experience
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end
  def create
    @message = Message.new message_params
    MessageMailer.submission(@message).deliver_now
    respond_to do |format|
      format.js
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :firstname, :email, :body)
  end

end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def index
    @experiences = Experience.all
    @message = Message.new
  end

  def download_pdf
    pdf_filename = File.join(Rails.root, "/app/assets/images/pdf/resume.pdf")
    send_file(pdf_filename, :filename => "resume.pdf", :type => "application/pdf", disposition: 'inline')
  end
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/layouts/_contact.html.haml
#contact
  .row
    .col-lg-6.contact-buttons-container
      .image-contact
      .layer
      .contact-buttons.text-center.wow.fadeInLeft
        %a.btn.btn-theme{href: "https://www.linkedin.com/in/am%C3%A9lie-delory-9707b111b/", target: "_blank"}
          = image_tag 'contact/in.png', class: "icon-white icon-contact", title: 'Linked In'
        %a.btn.btn-theme{href: "https://soundcloud.com/key-brain-chemical", target: "_blank"}
          = image_tag 'contact/soundcloud.png', class: "icon-white icon-contact"
        %a.btn.btn-theme{href: "https://slides.com/amelie-d#_=_", target: "_blank"}
          = image_tag 'contact/shift.png', class: "icon-white icon-contact"
        %a.btn.btn-theme{href: "https://framagit.org/AmelieD", target: "_blank"}
          = image_tag 'contact/git.png', class: "icon-white icon-contact"



    .col-lg-6.darker-bg
      .contact-form
        .wow.fadeInLeft
          %h3.title-lg.light Contact
        = form_for @message, remote: true, id: 'contact-form', url: messages_path do |f|
          .row
            .col-md-6
              .form-group.wow.fadeInLeft
                .error
                = f.text_field  :name, required: true, placeholder: "Nom", class: "form-control"
            .col-md-6
              .form-group.wow.fadeInLeft
                = f.text_field  :firstname, required: true, placeholder: "Prénom", class: "form-control"
          .row
            .col-md-12
              .form-group.wow.fadeInLeft
                = f.email_field :email, required: true,placeholder: "Email" ,class: "form-control"
          .row
            .col-md-12
              .form-group.wow.fadeInLeft
                = f.text_area :body,  required: true, placeholder: 'Message', class: "form-control"
          .row
            .col-md-12
              %button.submit.btn.btn-theme.wow.fadeInLeft.initial-content
                %span Envoyer
              %button.btn.btn-theme.sent-content.hide.no_cursor
                %span Message envoyé, merci !
    .baniere.text-center
      .row
        .col-12.col-md-4.contact-item
          = image_tag 'contact/phone.png'
          %br
          %span.light 06 20 00 35 44
        .col-12.col-md-4.contact-item
          = image_tag 'contact/email.png'
          %br
          %span.light amelie.delory@hotmail.fr
        .col-12.col-md-4.contact-item
          = image_tag 'contact/location.png'
          %br
          %span.light Arras

app/views/layouts/_svg_mouse.html.haml
%svg{:height => "100%", :style => "fill-rule:evenodd;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:1.5;", :version => "1.1", :viewbox => "0 0 247 390", :width => "40px", :xmlns => "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink"}
  %path#wheel{:d => "M123.359,79.775l0,72.843", :style => "fill:none;stroke:#fff;stroke-width:20px;"}
  %path#mouse{:d => "M236.717,123.359c0,-62.565 -50.794,-113.359 -113.358,-113.359c-62.565,0 -113.359,50.794 -113.359,113.359l0,143.237c0,62.565 50.794,113.359 113.359,113.359c62.564,0 113.358,-50.794 113.358,-113.359l0,-143.237Z", :style => "fill:none;stroke:#fff;stroke-width:20px;"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}

    %title
      = controller_name == 'resume' ? 'Amélie Delory' : 'MATUVU'
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/wow/0.1.12/wow.min.js"
    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag params[:controller]

    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/jquery.validate.min.js"
    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/additional-methods.min.js"

  %body{'data-spy': "scroll", 'data-target': "#scrollspy", 'data-offset': 50, id: 'srollspy-content'}
    = yield

app/views/resume/_about.html.haml
#about
  .container
    .row
      .col-lg-5
        .image-container
          .layer-me
          = image_tag 'img_cv_big.jpg', class: 'me'

      .col-lg-7
        #about-tab.nav.nav-pills{ :role => "tablist"}
          %a#infos-tab.btn-about.active.col-4{"data-toggle" => "pill", :href => "#page1", :role => "tab"}
            = image_tag "user.png", class:'about-logo'
            Infos
          %a#vision-tab.btn-about.col-4{"data-toggle" => "pill", :href => "#page2", :role => "tab"}
            = image_tag "eye.png", class:'about-logo'
            Vision
          %a#contact-tab.btn-about.col-4{"data-toggle" => "pill", :href => "#page3", :role => "tab"}
            = image_tag "paperplane.png", class:'about-logo'
            Contact
        .row
          .col-md-12
            #about-tabContent.tab-content
              #page1.tab-pane.fade.show.active{"aria-labelledby" => "infos-tab", :role => "tabpanel"}
                %h5 Infos
                %p Nom : Delory
                %p Prénom : Amélie
                %p Date : 1992
                %p Tél : 06 20 00 35 44
                %p Mail : amelie.delory@hotmail.fr
                %p Ad : 6 hameau des Cailles, 62223 St Nicoals
              #page2.tab-pane.fade{"aria-labelledby" => "vision-tab", :role => "tabpanel"}
                %h5 Vision
                %p
                  Le Web nous offre aujourd'hui un espace de libert&#xE9; cr&#xE9;atif et d'expression.
                  C'est avant tout ce qui me passionne dans cet univers o&#xF9; nous sommes au coeur du Language,
                  mati&#xE8;re premi&#xE8;re qui donne vie &#xE0; nos id&#xE9;es et nos projets, qu'ils soient simples ou compl&#xE8;tement d&#xE9;lirants...
                  Son &#xE9;volution constante anime mon envie d'apprendre, de cr&#xE9;er, d'am&#xE9;liorer, d'optimiser les techniques de d&#xE9;veloppement et de design, afin de concr&#xE9;tiser ces projets de la fa&#xE7;on la plus adapt&#xE9;e possible.
              #page3.tab-pane.fade{"aria-labelledby" => "contact-tab", :role => "tabpanel"}



              -#
              -# %a.btn.btn-about.wow.fadeInLeft{'data-wow-offset': 0} Vision
              -# %a.btn.btn-about.wow.fadeInLeft{'data-wow-offset': 0} Coordonnées
              -#
              -# %a.btn.btn-theme.wow.fadeInLeft{'data-wow-offset': 0} Me contacter
              -# %ul#myTab.nav.nav-tabs{:role => "tablist"}
              -#   %li.nav-item
              -#     %a#infos-tab.nav-link.active{"aria-controls" => "home", "aria-selected" => "true", "data-toggle" => "tab", :href => "#home", :role => "tab"} Coordonnées
              -#   %li.nav-item
              -#     %a#vision-tab.nav-link{"aria-controls" => "profile", "aria-selected" => "false", "data-toggle" => "tab", :href => "#profile", :role => "tab"} Vision
              -#   %li.nav-item
              -#     %a#contact-tab.nav-link{"aria-controls" => "contact-form", "aria-selected" => "false", "data-toggle" => "tab", :href => "#contact-form", :role => "tab"} Contact
              -# #myTabContent.tab-content
              -#   #infos.tab-pane.fade.show.active{"aria-labelledby" => "home-tab", :role => "tabpanel"}
              -#     %h4 Coordonnées
              -#
              -#   #vision.tab-pane.fade{"aria-labelledby" => "profile-tab", :role => "tabpanel"}
              -#     %h4 Vision
              -#
              -#
              -#     %p
              -#       Le Web nous offre aujourd'hui un espace de libert&#xE9; cr&#xE9;atif et d'expression.
              -#       C'est avant tout ce qui me passionne dans cet univers o&#xF9; nous sommes au coeur du Language,
              -#       mati&#xE8;re premi&#xE8;re qui donne vie &#xE0; nos id&#xE9;es et nos projets, qu'ils soient simples ou compl&#xE8;tement d&#xE9;lirants...
              -#       Son &#xE9;volution constante anime mon envie d'apprendre, de cr&#xE9;er, d'am&#xE9;liorer, d'optimiser les techniques de d&#xE9;veloppement et de design, afin de concr&#xE9;tiser ces projets de la fa&#xE7;on la plus adapt&#xE9;e possible.
              -#
              -#   #contact-form.tab-pane.fade{"aria-labelledby" => "contact-tab", :role => "tabpanel"} ...

app/views/resume/_experience.html.haml
#experience
  .container
    .row
      .col-lg-12
        %h3.title-lg.mb-5.wow.bounceInLeft
          Expérience
    - @experiences.where(experience_type: 0).each do |work|
      .row.resume-card.wow.bounceInLeft
        .col-lg-3.location-date.light
          %h5.location-title= work.location
          %h6
            - if work.start_date.year != work.end_date.year
              = work.start_date.year
              = ' - '
            = work.end_date.year
        .col-lg-9.bg-white.description
          %h4.experience-title.mb-5= work.title
          %p= work.description
          .mb-5
          - work.skills.order(:priority).each do |s|
            .tag.wow.fadeInLeft= s.name

#education
  .container
    .row
      .col-lg-12
        %h3.title-lg.mb-5.wow.bounceInLeft
          Formation
    - @experiences.where(experience_type: 1).each do |education|
      .row.resume-card.wow.bounceInLeft
        .col-lg-3.location-date.light
          %h5.location-title= education.location
          %h6
            - if education.start_date.year != education.end_date.year
              = education.start_date.year
              = ' - '
            = education.end_date.year
        .col-lg-9.bg-white.description
          %h4.experience-title.mb-5= education.title
          %p= education.description
          .mb-5
          - education.skills.order(:priority).each do |s|
            .tag.wow.fadeInLeft= s.name

app/views/resume/_home.html.haml
#home
  .image-home
  .layer
    .svg-container
      = render 'layouts/svg_mouse.html.haml'
  .container
    .row
      .col-lg-8.col-offset-4
        .presentation
          .home-content
            %h1.name
              Amélie Delory
            %h2.ml
              DÉVELOPPEUSE
              %span.caroussel
                %span WEB
                %span FULL STACK
                %span RUBY ON RAILS
          .row
            .col-lg-12
              %a.btn.btn-theme.wow.fadeInLeft{href: '#contact', 'data-wow-offset': 0} CONTACT
              = link_to "TÉLÉCHARGER CV", download_pdf_path, target: '_blank', class: 'btn btn-theme wow fadeInRight'

app/views/resume/_portfolio.html.haml
#portfolio
  .container
    .row
      .col-lg-12.text-center.mb-5
        %h3.title-lg.wow.fadeInLeft Portfolio
    .row
      .col-md-6.grid.wow.fadeInLeft
        %figure.effect-chico
          %img
            = image_tag 'layers/home-1.jpg', class: 'portfolio-img'
          -# .layer-portfolio
          %figcaption
            %h2
              MATUVU
            %p Site web démo pour agence web. RoR. Bootstrap.
            %a.btn.btn-theme{:href => "/website", target: "_blank"} VOIR
      .col-md-6.grid.wow.fadeInLeft
        %figure.effect-chico
          %img
            = image_tag 'layers/minimal3.jpg', class: 'portfolio-img'
          -# .layer-portfolio
          %figcaption
            %h2
              CURRICULUM
            %p Vous y êtes ! Ceci est mon CV. RoR. Bootstrap.
            %a.btn.btn-theme.no_cursor VOUS Y ÊTES
      .col-md-6.grid.wow.fadeInLeft
        %figure.effect-chico
          %img
            = image_tag 'layers/minimal.jpg', class: 'portfolio-img'
          -# .layer-portfolio
          %figcaption
            %h2
              DAILY TECH
            %p Application web pour poster des articles sur des veilles technologiques. PHP
            %a.btn.btn-theme.no_cursor WIP

app/views/resume/_skills.html.haml
#skills
  .container
    .row
      .col-lg-12.text-center
        %h3.title-lg.mb-5.wow.fadeInDown Langages et frameworks
  .skills-background
    .layer-skills
    .container
      .row
        .col-lg-3.col-6.light-card.skill-card.d-flex
          %div{class:"align-items-center d-flex justify-content-center"}
            %h6.wow.fadeInLeft
              RUBY ON RAILS
        .col-lg-3.col-6.dark-card.skill-card.d-flex
          %div{class:"align-items-center d-flex justify-content-center"}
            %h6.wow.fadeInLeft
              HTML 5
              %br
              CSS 3
        .col-lg-3.col-6.light-card.d-flex.skill-card
          %div{class:"align-items-center d-flex justify-content-center"}
            %h6.wow.fadeInLeft
              JAVASCRIPT
              %br
              JQUERY
        .col-lg-3.col-6.dark-card.d-flex.skill-card
          %div{class:"align-items-center d-flex justify-content-center"}
            %h6.wow.fadeInLeft
              MYSQL

        .col-lg-3.col-6.dark-card.skill-card.d-flex
          %div{class:"align-items-center d-flex justify-content-center"}
            %h6.wow.fadeInLeft
              PHP
        .col-lg-3.col-6.light-card.skill-card.d-flex
          %div{class:"align-items-center d-flex justify-content-center"}
            %h6.wow.fadeInLeft
              WORDPRESS
        .col-lg-3.col-6.dark-card.skill-card.d-flex
          %div{class:"align-items-center d-flex justify-content-center"}
            %h6.wow.fadeInLeft
              BOOTSTRAP
        .col-lg-3.col-6.light-card.d-flex.skill-card
          %div{class:"align-items-center d-flex justify-content-center"}
            %h6.wow.fadeInLeft
              MATERIALIZE

app/views/resume/_tools.html.haml
#tools-panel
  .container
    .row
      .col-lg-12.text-center
        %h3.title-lg.title-margin Outils et environnement
    .row
      .col-lg-3
        .tool-card
          = image_tag "git.png", class: "tool-icon"
          %h5 Git

      .col-lg-3
        .tool-card
          = image_tag "slack.png", class: "tool-icon"
          %h5 Slack

      .col-lg-3
        .tool-card
          = image_tag "trello.png", class: "tool-icon"
          %h5 Trello

      .col-lg-3
        .tool-card
          = image_tag "linux.png", class: "tool-icon"
          %h5 Linux

app/views/resume/index.html.haml
%header
  %nav.navbar.navbar-expand-lg.navbar-dark#scrollspy
    .container
      %a.navbar-brand.hvr-sweep-to-right.brand-resume{:href => "#home"}
        AD
      %button.navbar-toggler{"aria-controls" => "navbar", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
          -# = image_tag 'menu.png', class: 'icon-white'
      #navbar.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto.scrollspy-example

          %li.nav-item
            %a.nav-link{:href => "#experience", 'data-toggle' => "collapse"} Expérience
          %li.nav-item
            %a.nav-link{:href => "#education", 'data-toggle' => "collapse"} Formation
          %li.nav-item
            %a.nav-link{:href => "#skills", 'data-toggle' => "collapse"} Compétences
          %li.nav-item
            %a.nav-link{:href => "#portfolio", 'data-toggle' => "collapse"} Portfolio
          %li.nav-item
            %a.nav-link{:href => "#contact", 'data-toggle' => "collapse"} Contact
%section
  = render 'home'
%section
  = render 'experience'
%section
  = render 'skills'
%section
  = render 'portfolio'
= render 'layouts/contact'

app/views/website/_home.html.haml
#home
  .image-home
  .layer
    .svg-container
      = render 'layouts/svg_mouse.html.haml'
  .container
    .row
      .col-lg-8
        .home-content
          %h1.ml.wow.fadeInLeft
            VOUS VOULEZ
            %span.caroussel
              %span UN SITE WEB
              %span ÊTRE VISIBLE
              %span DU SUR MESURE
    .row
      .col-lg-4
        -# %a.btn.btn-theme.contact-btn-home.wow.fadeInDown{'data-wow-offset': 0, href: "#contact"} Me contacter
        %p.wow.fadeInRight
          Matuvu vous accompagne dans la création ou la refonte de votre site web adapaté à votre métier.
          Vous voulez une solution intuitive, évolutive et maintenable, je suis à votre écoute pour réaliser votre projet.
    .row
      .col-lg-8
        %a.btn.btn-theme.wow.fadeInLeft{href: '#contact', 'data-wow-offset': 0} Me contacter
        %a.btn.btn-theme.wow.fadeInLeft{href: '/resume', target: '_blank', 'data-wow-offset': 0} Voir mon CV

app/views/website/_quality.html.haml
#quality
  .container
    .row
      .col-lg-12.text-center
        %h5.title-sm.wow.fadeInLeft plus
        %h3.title-lg.mb-5.wow.fadeInLeft Ma charte qualité
    .row
      .col-lg-4.col-md-6.col-sm-12.mb-4
        .quality-card.theme-dark-bg.text-white.wow.flipInX
          = image_tag "services/detail.png", class: 'quality-icon icon-white'
          %h5.title
            Sens du détail
          %p.text.light
            Chaque détail compte : le choix des couleurs, le style des ic&#xF4;nes et des boutons, la typographie ainsi que les illustrations.
      .col-lg-4.col-md-6.col-sm-12.mb-4
        .quality-card.lighter-grey-bg.wow.flipInY
          = image_tag "services/uniq.png", class: 'quality-icon icon-theme'
          %h5.title
            Design unique
          %p.text
            Création d'un univers graphique unique permettant de refléter au mieux votre identité et vos valeurs.
      .col-lg-4.col-md-6.col-sm-12.mb-4
        .quality-card.white-bg.wow.flipInX
          = image_tag "services/layers.png", class: 'quality-icon icon-theme'
          %h5.title
            Interfaces intuitives
          %p.text
            Expérience utilisateur agréable et fluide à travers des fonctionnalités simples et intelligibles.
      .col-lg-4.col-md-6.col-sm-12.mb-4
        .quality-card.white-bg.wow.flipInY
          = image_tag "services/responsive.png", class: 'quality-icon icon-theme'
          %h5.title
            Responsive design
          %p.text
            Navigation optimales grace à son design responsive qui ajuste automatiquement les dimensions de la page au support numérique utilisé.
      .col-lg-4.col-md-6.col-sm-12.mb-4
        .quality-card.darker-bg.text-white.wow.flipInX
          = image_tag "services/evolution.png", class: 'quality-icon icon-white'
          %h5.title
            Développement évolutif
          %p.text.light
            L'architecture de développement est pensé de sorte à pouvoir ajouter, modifier ou désactiver des fonctionnalités.
      .col-lg-4.col-md-6.col-sm-12.mb-4
        .quality-card.theme-light-bg.text-white.wow.flipInY
          = image_tag "services/support.png", class: 'quality-icon icon-white'
          %h5.title
            Produits maintenables
          %p.text.light
            Simplification de la maintenance et des mises à jours, rigueur dans le respect des normes de codage.

app/views/website/_services.html.haml
#services
  .container
    .row
      .col-lg-12.text-center
        %h5.title-sm.wow.fadeInDown Mes services
        %h3.title-lg.mb-5 Du sur mesure pour vos projets
    .row
      .col-lg-4.col-md-6.col-sm-12.mb-4
        .service-card.theme-dark-bg.text-white.wow.bounceInLeft
          .background-service
            = image_tag "services/network.png", class: "service-icon icon-white"
            .service-content
              %h5.service-item sites vitrine
              %p.light Soyez visible sur le web grâce à un site vitrine sur mesure, mettant en avant vos produits, services et valeurs.
      .col-lg-4.col-md-6.col-sm-12.mb-4
        .service-card.lighter-grey-bg.wow.bounceInDown
          .background-service
            = image_tag "services/support.png", class: "service-icon icon-theme"
            .service-content
              %h5.service-itemapplications Applications web
              %p Optimisez et automatisez vos tâches du quodidien à travers un développement spécifique à vos besoins.
      .col-lg-4.col-md-6.col-sm-12.mb-4
        .service-card.white-bg.wow.bounceInRight
          .background-service
            = image_tag "services/layers.png", class: "service-icon icon-theme"
            .service-content
              %h5.service-item intégration
              %p Traduction de maquettes graphiques en code, assemblant tous les &#xE9;lements de la mise en page du site web de fa&#xE7;on optimale.

app/views/website/_website.html.haml
#website
  .layer
  .row
    .col-lg-6.website-img
    .col-lg-6
      .visible-card.darker-bg
        .wow.fadeInLeft
          %h5.title-sm.light Soyez visible
          %h3.title-lg.light.mb-5 Un investissement sur le long terme
          %p
            Aujourd'hui, presque 90% des français se fient à leurs recherches sur le web avant d'acheter un service ou un produit.
            %br
            Votre site vitrine, c’est une porte de communication et de présentation pour vous, ce que vous faites et vos valeurs, disponible en tout temps et accessible de partout.
            %br
            Le simple fait d'exister sur le web augmente votre notoriété et renforce votre crédibilité.
            %br
          %br
          %strong
            %a.btn.btn-theme{href: "#contact"} Parlez moi de votre projet

app/views/website/index.html.haml
%header
  %nav.navbar.navbar-expand-lg.navbar-dark#scrollspy
    .container
      %a.navbar-brand.hvr-sweep-to-right.brand-website{:href => "#home"}
        = image_tag 'mountain.png', class: 'navbar-logo icon-white'
        Matuvu
      %button.navbar-toggler{"aria-controls" => "navbar", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbar.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto
          %li.nav-item
            %a.nav-link{:href => "#services"} Services
          %li.nav-item
            %a.nav-link{:href => "#quality"} Charte qualité
          %li.nav-item
            %a.nav-link{:href => "#contact"} Contact


%section
  = render 'home'
  = render 'services'
  = render 'website'
  = render 'quality'
  = render 'layouts/contact'